experiment_name: Test
experiments_path: ./experiments/

optimizer_name: Adam
optimizer_params: {}

scheduler_name: StepLR
scheduler_params:
  step_size: 100
  gamma: 0.95

model_params: {}

training_params:
  use_log_output: False

train_dataset_params:
  filename: train.csv

valid_dataset_params:
  filename: train.csv

dataloader_params:
  train_batch_size: 32
  val_batch_size: 32
  num_workers: 0

model_checkpoint_params:
  monitor: valid/loss
  filename: checkpoint-epoch{epoch:02d}-valid_loss{valid/loss:.2f}
  auto_insert_metric_name: False
  save_last: True
  save_top_k: 3

trainer_params:
  gpus: 0
  max_epochs: 100
  check_val_every_n_epoch: 1
